FROM node:latest

ENV APP_ROOT=/app 
ENV APP_PORT=3000

WORKDIR ${APP_ROOT}

ADD main.js .
ADD package.json .
ADD public public
ADD views views

RUN npm install

EXPOSE ${APP_PORT}

HEALTHCHECK --interval=30s --timeout=6s --retries=3 CMD curl -s -f http://localhost:${APP_PORT}/health > /dev/null || exit 1

ENTRYPOINT ["node", "./main.js"]