apiVersion: v1
kind: Service
metadata:
  name: fortune-svc
  namespace: myapp
spec:
  type: LoadBalancer
  selector:
    name: fortune
    version: v1
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP