apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-deployment
  namespace: myapp
  labels:
    name: fortune-deployment
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      name: fortune
      version: v1
  template:
    metadata: 
      name: fortune-pod
      labels:
        name: fortune
        version: v1
    spec:
      containers:
      - name: fortune-container
        image: geekwannabe555/fortune:latest
        imagePullPolicy: Always
        ports: 
        - name: http
          containerPort: 3000
        env:
        - name: APP_PORT
          value: "3000"
      
  