apiVersion: v1
kind: Secret
metadata:
  name: mydb-secret
  namespace: myapp
data:
  db_user: cm9vdA==
  db_password: Y2hhbmdlaXQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mydb-config
  namespace: myapp
data:
  db_host: db-svc
  db_port: "3306"
  db_user: root
