apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: myapp
spec:
  type: ClusterIP
  selector:
    name: db
    version: v1
  ports:
    - name: sql
      port: 3306
      targetPort: 3306
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: myapp
spec:
  type: LoadBalancer
  selector:
    name: app
    version: v1
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP